.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
.github/workflows/ci-dev.yml
.github/workflows/ci-prod.yml
.github/workflows/pull-request.yml

- pr, ci, cd workflow 파일
- application.yml, application-test.yml 등 설정을 안했기에 테스트 코드 오류나는게 정상일겁니다. 현재 application-test.yml이 존재하지 않기에 application.yml을 기반으로 test를 하려고하지만 db 설정 등 세팅을 해놓지 않았기에 오류납니다. 이부분은 ci/cd와 상관없기에 ci/cd 코드만 리뷰해주시면 됩니다.
- ec2, application.yml 등 다양한 환경변수도 아직 세팅이 되어있지 않아서 코드 자체 흐름만 파악하시면 됩니다.
- pr workflow는 자동입니다.
- ci workflow는 자동입니다.
- cd workflow는 수동입니다.
- X

[FEAT] CI/CD 구축

---

.github/workflows/ci-dev.yml
.github/workflows/ci-prod.yml
.gitmodules

- 서브모듈을 도입하여 *.yml 파일 관리
- ci에서 특정 .yml 파일을 시크릿 변수에서 가져오는게 아닌 서브모듈에서 가져 옴
- [서브모듈](https://velog.io/@junho5336/Git-Submodule%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90)

[REFACTOR] .yml 파일 서브모듈로 관리

---

.github/workflows/ci-dev.yml
.github/workflows/ci-prod.yml

- ci 파일에서 깃허브가 지원 안해주는 명령어를 삭제했습니다
- repository-variables 삭제
- X
- X

[FIX] CI 파일 오류 수정

---

.github/workflows/ci-dev.yml
.github/workflows/ci-prod.yml

- 깃허브 시크릿 저장 권한 부여
- secrets: write 권한 부여
- X
- X

[FIX] CI 깃허브 시크릿 저장 권한 부여

---

.github/workflows/ci-dev.yml
.github/workflows/ci-prod.yml

- 깃허브 cli 작동
- 깃허브 cli를 이용해 시크릿 키에 저장
- X
- X

[FIX] CI 깃허브 시크릿 저장 권한 부여 Develop

---

.github/workflows/ci-dev.yml
.github/workflows/ci-prod.yml
Dockerfile

- 이미지 생성을 위한 도커 파일 작성
- 도커 파일 작성
- ci 할 때 프로파일 별 빌드
- X

[FEAT] Docker File 작성

---

src/main/java/doldol_server/doldol/rollingPaper/entity/Message.java

- lazy loading 추가
- message에 lazy 로딩 추가

Refactor/#12: lazy 설정

---

src/main/java/doldol_server/doldol/complaint/entity/Complaint.java
src/main/java/doldol_server/doldol/complaint/entity/complaint.java
src/main/java/doldol_server/doldol/rollingPaper/entity/Participant.java
src/main/java/doldol_server/doldol/user/Role.java
src/main/java/doldol_server/doldol/user/SocialType.java
src/main/java/doldol_server/doldol/user/User.java

- 신고와 참여 내역 엔티티를 생성하고, 연결 관계를 설정해주었습니다.
- 신고 엔티티의 신고자/관리자 -> 유저 엔티티와 조인 (ManyToOne)
- 신고 엔티티의 롤링페이퍼 정보 -> 롤링페이퍼 엔티티와 조인 (ManyToOne)
- 신고 엔티티의 메시지 정보 -> 메시지 엔티티와 조인 (ManyToOne)
- 참여 내역의 참여자 정보 -> 유저 엔티티와 조인 (ManyToOne)
- 참여 내역의 롤링페이퍼 정보 -> 롤링페이퍼 엔티티와 조인 (ManyToOne)
- 참여 내역의 메시지 정보 -> 메시지 엔티티와 조인 (OnetoOne)
- DolDol ERD Cloud

[FEAT] 도메인 - 신고, 참여 내역

---

src/main/java/doldol_server/doldol/report/entity/Report.java
src/main/java/doldol_server/doldol/rollingPaper/entity/Message.java
src/main/java/doldol_server/doldol/rollingPaper/entity/Paper.java
src/main/java/doldol_server/doldol/rollingPaper/entity/Participant.java

- 도메인 수정
- 기획에 맞게 도메인 객체 수정
- 엔티티 이름 변경
- 베이스 엔티티 도입
- 기본 생성자 어노테이션 추가

[REFACTOR] 도메인 수정

---

src/main/java/doldol_server/doldol/auth/controller/AuthController.java
src/main/java/doldol_server/doldol/auth/dto/request/JoinRequest.java
src/main/java/doldol_server/doldol/common/config/SecurityConfig.java
src/main/java/doldol_server/doldol/report/controller/ReportController.java
src/main/java/doldol_server/doldol/report/dto/request/ReportRequest.java
src/main/java/doldol_server/doldol/report/dto/response/ReportResponse.java
src/main/java/doldol_server/doldol/rollingPaper/controller/MessageController.java
src/main/java/doldol_server/doldol/rollingPaper/controller/PaperController.java
src/main/java/doldol_server/doldol/rollingPaper/controller/ParticipantController.java
src/main/java/doldol_server/doldol/rollingPaper/dto/request/CreateMessageRequest.java
src/main/java/doldol_server/doldol/rollingPaper/dto/request/DeleteMessageRequest.java
src/main/java/doldol_server/doldol/rollingPaper/dto/request/JoinPaperRequest.java
src/main/java/doldol_server/doldol/rollingPaper/dto/request/PaperRequest.java
src/main/java/doldol_server/doldol/rollingPaper/dto/request/UpdateMessageRequest.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageListResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperListResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/ParticipantResponse.java
src/main/java/doldol_server/doldol/rollingPaper/entity/MessageType.java

- #11 
- 일단 글자수 같은 디테일한 부분들은 신경쓰지 못했습니다,, 또한 제가 피그마통해서 알아서 해석한 부분도 많아서 추후에 바뀔 부분이 많을 것 같은 명세서입니다!
- 스웨거를 사용해보지 않았더라도, 테스트하기 편리하도록 구성했습니다 😚
- 궁금한 점 있거나 부족한 부분 있다면 꼬옥 말해주세요!!

[FEAT] swagger 기반 API 명세서 추가

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml

- cd 과정에서 설정해놓은 app 디렉토리 경로가 ec2와 다르게 설정되어있어서 변경했습니다.
- /app에서 ~/app으로 변경
- X

[FIX] app 디렉토리 경로 변경

---

src/main/java/doldol_server/doldol/auth/filter/CustomLogoutFilter.java
src/main/java/doldol_server/doldol/auth/filter/CustomUsernamePasswordAuthenticationFilter.java
src/main/java/doldol_server/doldol/auth/handler/CustomOAuth2SuccessHandler.java
src/main/java/doldol_server/doldol/auth/jwt/TokenProvider.java
src/main/java/doldol_server/doldol/auth/util/CookieUtil.java
src/main/java/doldol_server/doldol/auth/util/ResponseUtil.java
src/main/java/doldol_server/doldol/common/constants/CookieConstant.java
src/main/java/doldol_server/doldol/common/exception/errorCode/AuthErrorCode.java
src/main/resources/application.yml
src/test/java/doldol_server/doldol/auth/controller/AuthControllerTest.java
src/test/java/doldol_server/doldol/auth/jwt/TokenProviderTest.java

- 인증/인가 리팩토링했습니다. yml 파일 수정, AT를 쿠키에 담아서 전송했습니다. 토큰 만료 오류 코드를 상세히 보냈습니다.
- yml 파일 수정
- AT를 쿠키에 담아서 전송
- 토큰 만료 오류 코드 전송
- X

[REFACTOR] 인증/인가 리팩토링

---

src/main/java/doldol_server/doldol/common/config/CorsConfig.java
src/main/java/doldol_server/doldol/common/constants/CorsConstant.java

- cors 문제 해결
- http:// 명시하여 localhost:3000, localhost:3001 추가
- @Value 값은 기본적으로 static 변수에 할당되지 않음
- [@Value 관련](https://velog.io/@beomsu/static-%EB%A9%94%EC%84%9C%EB%93%9C%EC%97%90%EC%84%9C-Value-%EA%B0%92-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)

[FIX] cors 문제 해결

---

src/main/java/doldol_server/doldol/common/constants/CorsConstant.java

-
-
-
-
- [Title](https://...)

[FIX] cors 문제

---

src/main/java/doldol_server/doldol/auth/controller/AuthController.java
src/main/java/doldol_server/doldol/auth/filter/CustomLogoutFilter.java
src/main/java/doldol_server/doldol/auth/util/ResponseUtil.java

- 로그아웃 시 응답 204 반환
- 로그아웃 시 응답 204 반환
- X

[REFACTOR] 인증/인가 API 리팩토링

---

src/main/java/doldol_server/doldol/rollingPaper/controller/PaperController.java
src/main/java/doldol_server/doldol/rollingPaper/controller/ParticipantController.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperDetailResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperResponse.java
src/main/java/doldol_server/doldol/rollingPaper/repository/ParticipantRepository.java
src/main/java/doldol_server/doldol/rollingPaper/service/PaperService.java
src/main/java/doldol_server/doldol/rollingPaper/service/ParticipantService.java

- 롤링페이퍼 개별 조회 API
- ResponseEntity 삭제
- 개별 조회 기능 (방장여부, 오픈시간 포함)

[FEAT] 페이퍼 개별 조회 API

---

src/main/java/doldol_server/doldol/auth/util/CookieUtil.java
src/main/resources/application.yml

[FIX] 쿠키 도메인 설정

---

src/main/java/doldol_server/doldol/common/dto/CursorPage.java
src/main/java/doldol_server/doldol/report/controller/ReportController.java
src/main/java/doldol_server/doldol/report/service/ReportService.java
src/main/java/doldol_server/doldol/rollingPaper/controller/ParticipantController.java
src/main/java/doldol_server/doldol/rollingPaper/dto/request/GetParticipantsRequest.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageListResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperListResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/ParticipantResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/ParticipantsCursorResponse.java
src/main/java/doldol_server/doldol/rollingPaper/entity/Participant.java
src/main/java/doldol_server/doldol/rollingPaper/repository/ParticipantRepository.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/ParticipantRepositoryCustom.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/ParticipantRepositoryCustomImpl.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/main/java/doldol_server/doldol/rollingPaper/service/PaperService.java
src/main/java/doldol_server/doldol/rollingPaper/service/ParticipantService.java
src/main/java/doldol_server/doldol/user/entity/User.java
src/test/java/doldol_server/doldol/report/service/ReportServiceTest.java
src/test/java/doldol_server/doldol/rollingPaper/controller/MessageControllerTest.java

- 참여자 조회에 커서 페이징 추가
- 참여자를 이름순으로 조회하기 위해 유저 테이블에 인덱스 추가
X

[REFACTOR] 참여자 조회에 페이지네이션 추가

---

src/main/java/doldol_server/doldol/rollingPaper/dto/response/CreatePaperResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperDetailResponse.java
src/main/java/doldol_server/doldol/rollingPaper/service/PaperService.java

- #116 
- 초대 코드 추가
- 롤링페이퍼 생성, 개별 조회 시 초대 코드 추가

[REFACTOR] 초대 코드 추가

---

src/main/java/doldol_server/doldol/auth/controller/AuthController.java
src/main/java/doldol_server/doldol/auth/service/AuthService.java
src/main/java/doldol_server/doldol/common/config/SecurityConfig.java
src/main/java/doldol_server/doldol/user/entity/User.java
src/test/java/doldol_server/doldol/auth/controller/AuthControllerTest.java

- 탈퇴시 쿼리파라미터로 user Id 받기
- 탈퇴시 쿼리파라미터로 user Id 받기
- X

[FIX] 탈퇴시 쿼리파라미터로 user Id 받기

---

src/main/java/doldol_server/doldol/rollingPaper/controller/MessageController.java
src/main/java/doldol_server/doldol/rollingPaper/dto/request/PaperRequest.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/CreatePaperResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperDetailResponse.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperResponse.java
src/main/java/doldol_server/doldol/rollingPaper/entity/Paper.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/test/java/doldol_server/doldol/rollingPaper/controller/MessageControllerTest.java
src/test/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImplTest.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java

- 롤링페이퍼 오픈 날짜 시간 삭제 및 검증 추가
- 날짜만 유지
- 오픈 날짜가 과거면 에러
X

[REFACTOR] 롤링페이퍼 오픈 날짜 관련

---

src/main/java/doldol_server/doldol/auth/handler/CustomOAuth2FailureHandler.java
src/test/resources/application-test.yml

- 소셜 회원가입 과정에서 동의 취소 할 시 로그인 폼으로 리다이렉션
-소셜 회원가입 과정에서 동의 취소 할 시 로그인 폼으로 리다이렉션
- X

[FIX] 소셜 회원가입 과정에서 동의 취소 할 시 로그인 폼으로 리다이렉션

---

src/main/java/doldol_server/doldol/auth/controller/AuthController.java
src/main/java/doldol_server/doldol/auth/service/AuthService.java
src/main/java/doldol_server/doldol/common/exception/errorCode/AuthErrorCode.java
src/main/java/doldol_server/doldol/user/repository/UserRepository.java
src/test/java/doldol_server/doldol/auth/controller/AuthControllerTest.java
src/test/java/doldol_server/doldol/auth/service/AuthServiceTest.java

- 아이디/비번 찾을 때 이름도 추가 검증
- 아이디/비번 찾을 때 이름도 추가 검증
- X

[REFACTOR] 아이디/비번 찾을 때 이름도 추가 검증

---

src/main/java/doldol_server/doldol/rollingPaper/controller/MessageController.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/test/java/doldol_server/doldol/rollingPaper/controller/MessageControllerTest.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java

- 메세지 수정하기 전 get으로 단건 메세지의 정보 가져오기
- messageId를 바탕으로 MessageResponse 반환
- X

[FEAT] 메시지 개별 조회 API 요청

---

src/main/java/doldol_server/doldol/common/exception/errorCode/MessageErrorCode.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageResponse.java
src/main/java/doldol_server/doldol/rollingPaper/repository/MessageRepository.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustom.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/test/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImplTest.java

- #151 #153 #154 #155 
- user id를 반환
- X

[FIX] 각 이슈에 대한 해결

---

src/main/java/doldol_server/doldol/rollingPaper/controller/MessageController.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/test/java/doldol_server/doldol/rollingPaper/controller/MessageControllerTest.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java

- 메시지 리스트 조회 시, 공개 날짜 파라미터 제외 요청
- 메시지 리스트 조회 시, 공개 날짜 파라미터 제외 요청
- X

[REFACTOR] 메시지 리스트 조회 시, 공개 날짜 파라미터 제외 요청

---

src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageResponse.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java
src/test/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImplTest.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java

- user name 반환
- user name 반환
- X

[FIX] user name 반환

---

src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageResponse.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/test/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImplTest.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java

- RECIEVE일때만 content가 null 처리
- RECIEVE일때만 content가 null 처리
- X

[FIX] RECIEVE일때만 content가 null 처리

---

src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java
src/test/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImplTest.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java

- 페이지네이션 cursor id 계산 수정
- 페이지네이션 cursor id 계산 수정
- X

[FIX] 페이지네이션 cursor id 계산 수정

---

src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java

- 메세지 공개 날짜 수정
- 메세지 공개 날짜 수정
- X

[FIX] 메세지 공개 날짜 수정

---

src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustom.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java

- 받은 메세지도 삭제 가능
-받은 메시지 삭제 가능
- X

[BUG] 받은 메시지 삭제 이슈 해결

---

src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustom.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/main/resources/application.yml

- 프론트 서버 주소 변경
- 프론트 서버 주소 변경
- X

[REFACTOR] 프론트 서버 주소 변경

---

src/main/java/doldol_server/doldol/report/controller/AdminReportController.java
src/main/java/doldol_server/doldol/report/dto/request/ReportRequest.java
src/main/java/doldol_server/doldol/report/dto/response/ReportResponse.java
src/main/java/doldol_server/doldol/report/entity/Report.java
src/main/java/doldol_server/doldol/report/repository/custom/ReportRepositoryCustom.java
src/main/java/doldol_server/doldol/report/repository/custom/ReportRepositoryImpl.java
src/main/java/doldol_server/doldol/report/service/ReportService.java
src/test/java/doldol_server/doldol/report/service/ReportServiceTest.java

- 신고 API 수정
- 신고 생성 시, 메시지 soft delete
- 신고 제목, 내용 필드 삭제
-

Refactor: #182 soft delete message when report is created

---

build.gradle
src/main/java/doldol_server/doldol/rollingPaper/repository/ParticipantRepository.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/ParticipantRepositoryCustom.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/ParticipantRepositoryCustomImpl.java
src/main/java/doldol_server/doldol/rollingPaper/service/ParticipantService.java

-
-
-
-
- [Title](https://...)

[FIX] 제발 마지막

---

build.gradle
src/main/java/doldol_server/doldol/auth/service/AuthService.java
src/main/java/doldol_server/doldol/auth/service/CustomOAuth2UserService.java
src/main/java/doldol_server/doldol/auth/service/CustomUserDetailsService.java
src/main/java/doldol_server/doldol/common/config/JasyptConfig.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageResponse.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/test/java/doldol_server/doldol/auth/service/AuthServiceTest.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java
src/test/resources/application-test.yml

- jasypt 암호화 추가
- jasypt 암호화 추가
- X

[REFACTOR] jasypt 암호화 추가

---

build.gradle
src/main/java/doldol_server/doldol/auth/controller/TestController.java
src/main/java/doldol_server/doldol/auth/service/AuthService.java
src/main/java/doldol_server/doldol/auth/service/CustomOAuth2UserService.java
src/main/java/doldol_server/doldol/auth/service/CustomUserDetailsService.java
src/main/java/doldol_server/doldol/auth/service/TestService.java
src/main/java/doldol_server/doldol/common/config/JasyptConfig.java
src/main/java/doldol_server/doldol/common/config/SecurityConfig.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageResponse.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/main/java/doldol_server/doldol/user/entity/User.java
src/test/java/doldol_server/doldol/auth/service/AuthServiceTest.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java
src/test/resources/application-test.yml

[REFACTOR] DB 암호화 처리

---

src/main/java/doldol_server/doldol/auth/service/CustomUserDetailsService.java

-
-
-
-
- [Title](https://...)

[FIX] Auth 관련 암호화 롤백

---

src/main/java/doldol_server/doldol/auth/service/CustomUserDetailsService.java
src/main/java/doldol_server/doldol/auth/service/TestService.java

- 메세지 내용 암호화 설정
- 메세지 내용 암호화 설정
- X

[FIX] 메세지 내용 암호화 설정

---

build.gradle
src/main/java/doldol_server/doldol/auth/controller/TestController.java
src/main/java/doldol_server/doldol/auth/service/TestService.java
src/main/java/doldol_server/doldol/common/config/JasyptConfig.java
src/main/java/doldol_server/doldol/common/config/SecurityConfig.java
src/main/java/doldol_server/doldol/rollingPaper/dto/response/MessageResponse.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/test/java/doldol_server/doldol/rollingPaper/service/MessageServiceTest.java
src/test/resources/application-test.yml

- prod 서버 메세지 암호화
- prod 서버 메세지 암호화
- X

[BUG] prod 서버 메세지 암호화

---

src/main/java/doldol_server/doldol/rollingPaper/entity/Paper.java
src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java

- 메세지 관련 N+1 해결
- 초대 코드 인덱싱
- 메세지 조회시 유저 명을 fetch join을 통해 N+1 해결
- 초대 코드 인덱싱
- X

[REFACTOR] 성능 개선

---

src/main/java/doldol_server/doldol/rollingPaper/repository/PaperRepository.java
src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
src/main/java/doldol_server/doldol/rollingPaper/service/ParticipantService.java
src/main/java/doldol_server/doldol/user/entity/User.java

- SQL문 쿼리 개선
- Paper의 날짜 데이터만 추출
- 연관 관계에서 해당 엔티티를 조회하는게 아닌, new를 통해 연관 관계 세팅
- X

[REFACTOR] SQL문 쿼리 개선
